# This is a sample file, for detailed reference see: https://rudderlabs.github.io/pywht/
models:
  - name: &model_name shopify_churn
    model_type: python_model
    model_spec:
      occurred_at_col: insert_ts
      entity_key: user
      validity_time: 24h # 1 day
      py_repo_url: git@github.com:rudderlabs/rudderstack-profiles-classifier.git

      train:
        file_extension: .json
        file_validity: 168h # If the last trained model is older than this, then the model will be trained again,
        inputs:
          - packages/feature_table/models/shopify_user_features # inputs to materialise the required data for model
        config:
          data: &model_data_input_configs
            package_name: feature_table # Name of the package where the profiles feature table is defined (declared in pb_project.yaml packages)
            label_column: is_churned_7_days # Name of column for which we want to find predictions
            label_value: 1 # Value of label column for which prediction is generated
            prediction_horizon_days: 7 # Number of days in future for which we want to predict
            features_profiles_model: 'shopify_user_features' # Model name
            output_profiles_ml_model: *model_name # Name of output model based on current model to dinstinguish between multiple models

      predict:
        inputs:
          - packages/feature_table/models/shopify_user_features
        config:
          data: *model_data_input_configs # Use the same config as training
          outputs:
            column_names:
              percentile: &percentile_name percentile_churn_score_7_days # Name of column in output table having percentile score
              score: churn_score_7_days # Name of column in output table having probabilistic score
            feature_meta_data: &feature_meta_data
              features:
                - name: *percentile_name
                  description: 'Percentile of churn score. Higher the percentile, higher the probability of churn'

      <<: *feature_meta_data